# Generated by Django 3.0.4 on 2020-03-22 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_fac_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='saa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='sba',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='sca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='sa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Faculty'),
        ),
    ]
