# Generated by Django 3.0.4 on 2020-03-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200322_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='choice1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='choice10',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='choice11',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='choice12',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='choice13',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='choice14',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='choice15',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='choice16',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='choice17',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='choice18',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='choice19',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='choice2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='choice20',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='choice3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='choice4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='choice5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='choice6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='choice7',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='choice8',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='choice9',
            field=models.IntegerField(null=True),
        ),
    ]
