# Generated by Django 3.0.4 on 2020-03-22 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200322_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice10',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice11',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice12',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice13',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice14',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice15',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice16',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice17',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice18',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice19',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice20',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice4',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice5',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice6',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice7',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice8',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice9',
        ),
        migrations.CreateModel(
            name='choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.IntegerField(null=True)),
                ('choice2', models.IntegerField(null=True)),
                ('choice3', models.IntegerField(null=True)),
                ('choice4', models.IntegerField(null=True)),
                ('choice5', models.IntegerField(null=True)),
                ('choice6', models.IntegerField(null=True)),
                ('choice7', models.IntegerField(null=True)),
                ('choice8', models.IntegerField(null=True)),
                ('choice9', models.IntegerField(null=True)),
                ('choice10', models.IntegerField(null=True)),
                ('choice11', models.IntegerField(null=True)),
                ('choice12', models.IntegerField(null=True)),
                ('choice13', models.IntegerField(null=True)),
                ('choice14', models.IntegerField(null=True)),
                ('choice15', models.IntegerField(null=True)),
                ('choice16', models.IntegerField(null=True)),
                ('choice17', models.IntegerField(null=True)),
                ('choice18', models.IntegerField(null=True)),
                ('choice19', models.IntegerField(null=True)),
                ('choice20', models.IntegerField(null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
