# Generated by Django 3.0.4 on 2020-03-22 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200322_1404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='choices',
            new_name='choice',
        ),
    ]
