# Generated by Django 3.0.4 on 2020-03-22 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200322_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='ch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.choice'),
        ),
    ]
