# Generated by Django 3.0.4 on 2020-03-22 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200322_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ch',
        ),
        migrations.AddField(
            model_name='choice',
            name='student',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
            preserve_default=False,
        ),
    ]
