# Generated by Django 3.0.4 on 2020-03-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200322_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cfilled',
            field=models.BooleanField(default=False),
        ),
    ]
