# Generated by Django 3.0.4 on 2020-03-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student_cfilled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cfilled',
        ),
        migrations.AddField(
            model_name='choice',
            name='cfilled',
            field=models.BooleanField(default=False),
        ),
    ]
