# Generated by Django 3.0.4 on 2020-03-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20200322_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='to',
            field=models.BooleanField(default=False),
        ),
    ]
