# Generated by Django 3.0.4 on 2020-03-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='sa',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='sb',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='sc',
            field=models.IntegerField(null=True),
        ),
    ]
