# Generated by Django 3.0.4 on 2020-03-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20200323_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='sa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='sb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='sc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
